{% import '$CONDA_DEFAULT_ENV/toolset-info/config.yaml' as toolset %}

package:
  name: ilastik-feature-selection
  version: "0.123"

source:
  git_url: https://github.com/ilastik/ilastik-feature-selection
  # git_tag: 88d0454b44f006e9f8963ec3188d42e8b9243ecd
  git_tag: c96efa84afdf72de1aea6974b4475584fed8a940 # master 2017/05/04

build:
  number: 0
  string: py{{py}}_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}
  msvc_compiler: {{toolset.version}}  # [win]

requirements:
  build:
    - python 3.5*
    - setuptools

  run:
    - python 3.5*
    - numpy
    - scikit-learn

about:
  home: https://bitbucket.org/FabianIsensee/feature_selection_clean
  license: BSD
  license_file: LICENSE
  summary: 'A Python library for selecting features during image classification.'