package:
    name: wsdt
    version: 0.2.post5

source:
  git_url: https://github.com/ilastik/wsdt
  git_tag: d2f83e424de63216ca14580001f1c4f7ab24d7db # master 2017/05/04

build:
  number: 0
  string: py35_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}

requirements:
  build:
    - python 3.5*
    - setuptools

  run:
    - python 3.5*
    - numpy
    - vigra >=1.11
    - networkx

about:
  summary: Implementation of a distance-transform-based watershed algorithm
