package:
  name: ilastiktools
  version: "0.2.post4"

source:
  git_url: git://github.com/ilastik/ilastiktools.git
  git_tag: b1ccf0a6717e6778106d804fc999747e7b0a8d05 # master 2017/07/06
  patches:
    - python3_cmake.patch

build:
  features:
    - vc14
  number: 0
  detect_binary_files_with_prefix: true
  string: 0_gb1ccf0a
  msvc_compiler: 14.0  # [win]

requirements:
  build:
    - python   3.5*
    - numpy    >=1.10
    - vigra    1.11.*
    - boost    1.64.*

  run:
    - python   3.5*
    - numpy    >=1.10
    - vigra    1.11.*
    - boost    1.64.*

about:
  home: http://ilastik.org
  license: GPLv3
  summary: Various compiled utilities for the ilastik project
